### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#142]
Despite my desire to keep our pull request experience light and easy, I think having some basic linting would be helpful.

Can somebody set up a lint check in our `Makefile` and have travis run it?

**Comment by k4k** [comment]
In looking around at options for this, it seems linting a Makefile is more difficult than it may appear on the surface. Can we try to identify some specific goals for the linter? From looking at the make file now it looks like this would be a good start:

* Whitespaces
* Unused variables
* `make all --dry-run`

**Comment by xmudrii** [comment]
‎I believe @kris-nova is talking about linting Go code rather than linting Makefile.

It could be done same as `gofmt`, just to make sure user actually has golint installed (do `go get`)

**Comment by k4k** [comment]
@xmudrii Go lint is already being run by virtue of runnin `make compile` in the existing tests. Do we want to split these lint checks out separately from the build checks?

**Comment by xmudrii** [comment]
‎That's not lint, take a look at this https://github.com/golang/lint

**Comment by MyDigitalLife** [comment]
Fixed with #170. We got about 240 warnings about name formatting, adding comments and not using under scores in names. I can easily fix the name formatting but the comments is probably something @kris-nova should fix seeing she wrote most of the existing code and knows best what this are and do.

**Comment by xmudrii** [comment]
Partially fixed with #187

**Comment by kris-nova** [comment]
Update? Are we linting yet? I haven't gone through and written a ton of code docs so I assume we still have at least 1 more step to go right?

**Comment by MyDigitalLife** [comment]
The docs is definitely still a open issue and with the code of the last few days there are probably a few more now. I would love if we can handle this ASAP and then add it to Travis. This way it will be mandatory for the project to have no linting errors.

**Comment by paulczar** [comment]
Here's a PR to enable bash script linting: https://github.com/kris-nova/kubicorn/pull/340
